/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ServerRequiredRouteImport } from './routes/_serverRequired'
import { Route as ServerRequiredWelcomeRouteImport } from './routes/_serverRequired/welcome'
import { Route as ServerRequiredVerifyEmailRouteImport } from './routes/_serverRequired/verify-email'
import { Route as ServerRequiredResetPasswordRouteImport } from './routes/_serverRequired/reset-password'
import { Route as ServerRequiredRegisterRouteImport } from './routes/_serverRequired/register'
import { Route as ServerRequiredLoginRouteImport } from './routes/_serverRequired/login'
import { Route as ServerRequiredForgotPasswordRouteImport } from './routes/_serverRequired/forgot-password'
import { Route as ServerRequiredAuthenticatedRouteImport } from './routes/_serverRequired/_authenticated'
import { Route as ServerRequiredAuthenticatedIndexRouteImport } from './routes/_serverRequired/_authenticated/index'
import { Route as ServerRequiredOidcCallbackRouteImport } from './routes/_serverRequired/oidc.callback'
import { Route as ServerRequiredInviteCodeRouteImport } from './routes/_serverRequired/invite.$code'
import { Route as ServerRequiredAuthenticatedUserStatsRouteImport } from './routes/_serverRequired/_authenticated/user-stats'
import { Route as ServerRequiredAuthenticatedTasksRouteImport } from './routes/_serverRequired/_authenticated/tasks'
import { Route as ServerRequiredAuthenticatedSettingsRouteImport } from './routes/_serverRequired/_authenticated/settings'
import { Route as ServerRequiredAuthenticatedProjectsRouteImport } from './routes/_serverRequired/_authenticated/projects'
import { Route as ServerRequiredAuthenticatedProfileRouteImport } from './routes/_serverRequired/_authenticated/profile'
import { Route as ServerRequiredAuthenticatedNavigateRouteImport } from './routes/_serverRequired/_authenticated/navigate'
import { Route as ServerRequiredAuthenticatedMyProjectsRouteImport } from './routes/_serverRequired/_authenticated/my-projects'
import { Route as ServerRequiredAuthenticatedMyDocumentsRouteImport } from './routes/_serverRequired/_authenticated/my-documents'
import { Route as ServerRequiredAuthenticatedInitiativesRouteImport } from './routes/_serverRequired/_authenticated/initiatives'
import { Route as ServerRequiredAuthenticatedHypothesesRouteImport } from './routes/_serverRequired/_authenticated/hypotheses'
import { Route as ServerRequiredAuthenticatedDocumentsRouteImport } from './routes/_serverRequired/_authenticated/documents'
import { Route as ServerRequiredAuthenticatedCreatedTasksRouteImport } from './routes/_serverRequired/_authenticated/created-tasks'
import { Route as ServerRequiredAuthenticatedProfileIndexRouteImport } from './routes/_serverRequired/_authenticated/profile/index'
import { Route as ServerRequiredAuthenticatedTasksTaskIdRouteImport } from './routes/_serverRequired/_authenticated/tasks_.$taskId'
import { Route as ServerRequiredAuthenticatedTagsTagIdRouteImport } from './routes/_serverRequired/_authenticated/tags_.$tagId'
import { Route as ServerRequiredAuthenticatedSettingsGuildRouteImport } from './routes/_serverRequired/_authenticated/settings/guild'
import { Route as ServerRequiredAuthenticatedSettingsAdminRouteImport } from './routes/_serverRequired/_authenticated/settings/admin'
import { Route as ServerRequiredAuthenticatedProjectsProjectIdRouteImport } from './routes/_serverRequired/_authenticated/projects_.$projectId'
import { Route as ServerRequiredAuthenticatedProfileSecurityRouteImport } from './routes/_serverRequired/_authenticated/profile/security'
import { Route as ServerRequiredAuthenticatedProfileNotificationsRouteImport } from './routes/_serverRequired/_authenticated/profile/notifications'
import { Route as ServerRequiredAuthenticatedProfileInterfaceRouteImport } from './routes/_serverRequired/_authenticated/profile/interface'
import { Route as ServerRequiredAuthenticatedProfileImportRouteImport } from './routes/_serverRequired/_authenticated/profile/import'
import { Route as ServerRequiredAuthenticatedProfileDangerRouteImport } from './routes/_serverRequired/_authenticated/profile/danger'
import { Route as ServerRequiredAuthenticatedProfileAiRouteImport } from './routes/_serverRequired/_authenticated/profile/ai'
import { Route as ServerRequiredAuthenticatedInitiativesInitiativeIdRouteImport } from './routes/_serverRequired/_authenticated/initiatives_.$initiativeId'
import { Route as ServerRequiredAuthenticatedHypothesesHypothesisIdRouteImport } from './routes/_serverRequired/_authenticated/hypotheses_.$hypothesisId'
import { Route as ServerRequiredAuthenticatedGGuildIdRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId'
import { Route as ServerRequiredAuthenticatedDocumentsDocumentIdRouteImport } from './routes/_serverRequired/_authenticated/documents_.$documentId'
import { Route as ServerRequiredAuthenticatedSettingsGuildIndexRouteImport } from './routes/_serverRequired/_authenticated/settings/guild/index'
import { Route as ServerRequiredAuthenticatedSettingsAdminIndexRouteImport } from './routes/_serverRequired/_authenticated/settings/admin/index'
import { Route as ServerRequiredAuthenticatedGGuildIdIndexRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/index'
import { Route as ServerRequiredAuthenticatedSettingsGuildUsersRouteImport } from './routes/_serverRequired/_authenticated/settings/guild/users'
import { Route as ServerRequiredAuthenticatedSettingsGuildAiRouteImport } from './routes/_serverRequired/_authenticated/settings/guild/ai'
import { Route as ServerRequiredAuthenticatedSettingsAdminUsersRouteImport } from './routes/_serverRequired/_authenticated/settings/admin/users'
import { Route as ServerRequiredAuthenticatedSettingsAdminEmailRouteImport } from './routes/_serverRequired/_authenticated/settings/admin/email'
import { Route as ServerRequiredAuthenticatedSettingsAdminBrandingRouteImport } from './routes/_serverRequired/_authenticated/settings/admin/branding'
import { Route as ServerRequiredAuthenticatedSettingsAdminAuthRouteImport } from './routes/_serverRequired/_authenticated/settings/admin/auth'
import { Route as ServerRequiredAuthenticatedSettingsAdminAiRouteImport } from './routes/_serverRequired/_authenticated/settings/admin/ai'
import { Route as ServerRequiredAuthenticatedProjectsProjectIdSettingsRouteImport } from './routes/_serverRequired/_authenticated/projects_.$projectId_.settings'
import { Route as ServerRequiredAuthenticatedInitiativesInitiativeIdSettingsRouteImport } from './routes/_serverRequired/_authenticated/initiatives_.$initiativeId_.settings'
import { Route as ServerRequiredAuthenticatedGGuildIdSettingsRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/settings'
import { Route as ServerRequiredAuthenticatedGGuildIdQueuesRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/queues'
import { Route as ServerRequiredAuthenticatedGGuildIdProjectsRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/projects'
import { Route as ServerRequiredAuthenticatedGGuildIdInitiativesRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/initiatives'
import { Route as ServerRequiredAuthenticatedGGuildIdHypothesesRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/hypotheses'
import { Route as ServerRequiredAuthenticatedGGuildIdDocumentsRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/documents'
import { Route as ServerRequiredAuthenticatedDocumentsDocumentIdSettingsRouteImport } from './routes/_serverRequired/_authenticated/documents_.$documentId_.settings'
import { Route as ServerRequiredAuthenticatedGGuildIdSettingsIndexRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/settings/index'
import { Route as ServerRequiredAuthenticatedGGuildIdTasksTaskIdRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/tasks_.$taskId'
import { Route as ServerRequiredAuthenticatedGGuildIdTagsTagIdRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/tags_.$tagId'
import { Route as ServerRequiredAuthenticatedGGuildIdSettingsUsersRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/settings/users'
import { Route as ServerRequiredAuthenticatedGGuildIdSettingsAiRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/settings/ai'
import { Route as ServerRequiredAuthenticatedGGuildIdQueuesQueueIdRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/queues_.$queueId'
import { Route as ServerRequiredAuthenticatedGGuildIdProjectsProjectIdRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/projects_.$projectId'
import { Route as ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/initiatives_.$initiativeId'
import { Route as ServerRequiredAuthenticatedGGuildIdHypothesesHypothesisIdRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/hypotheses_.$hypothesisId'
import { Route as ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/documents_.$documentId'
import { Route as ServerRequiredAuthenticatedGGuildIdQueuesQueueIdSettingsRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/queues_.$queueId_.settings'
import { Route as ServerRequiredAuthenticatedGGuildIdProjectsProjectIdSettingsRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/projects_.$projectId_.settings'
import { Route as ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdSettingsRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/initiatives_.$initiativeId_.settings'
import { Route as ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdSettingsRouteImport } from './routes/_serverRequired/_authenticated/g/$guildId/documents_.$documentId_.settings'

const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRequiredRoute = ServerRequiredRouteImport.update({
  id: '/_serverRequired',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRequiredWelcomeRoute = ServerRequiredWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => ServerRequiredRoute,
} as any)
const ServerRequiredVerifyEmailRoute =
  ServerRequiredVerifyEmailRouteImport.update({
    id: '/verify-email',
    path: '/verify-email',
    getParentRoute: () => ServerRequiredRoute,
  } as any)
const ServerRequiredResetPasswordRoute =
  ServerRequiredResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => ServerRequiredRoute,
  } as any)
const ServerRequiredRegisterRoute = ServerRequiredRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ServerRequiredRoute,
} as any)
const ServerRequiredLoginRoute = ServerRequiredLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ServerRequiredRoute,
} as any)
const ServerRequiredForgotPasswordRoute =
  ServerRequiredForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => ServerRequiredRoute,
  } as any)
const ServerRequiredAuthenticatedRoute =
  ServerRequiredAuthenticatedRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => ServerRequiredRoute,
  } as any)
const ServerRequiredAuthenticatedIndexRoute =
  ServerRequiredAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredOidcCallbackRoute =
  ServerRequiredOidcCallbackRouteImport.update({
    id: '/oidc/callback',
    path: '/oidc/callback',
    getParentRoute: () => ServerRequiredRoute,
  } as any)
const ServerRequiredInviteCodeRoute =
  ServerRequiredInviteCodeRouteImport.update({
    id: '/invite/$code',
    path: '/invite/$code',
    getParentRoute: () => ServerRequiredRoute,
  } as any)
const ServerRequiredAuthenticatedUserStatsRoute =
  ServerRequiredAuthenticatedUserStatsRouteImport.update({
    id: '/user-stats',
    path: '/user-stats',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedTasksRoute =
  ServerRequiredAuthenticatedTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsRoute =
  ServerRequiredAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedProjectsRoute =
  ServerRequiredAuthenticatedProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedProfileRoute =
  ServerRequiredAuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedNavigateRoute =
  ServerRequiredAuthenticatedNavigateRouteImport.update({
    id: '/navigate',
    path: '/navigate',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedMyProjectsRoute =
  ServerRequiredAuthenticatedMyProjectsRouteImport.update({
    id: '/my-projects',
    path: '/my-projects',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedMyDocumentsRoute =
  ServerRequiredAuthenticatedMyDocumentsRouteImport.update({
    id: '/my-documents',
    path: '/my-documents',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedInitiativesRoute =
  ServerRequiredAuthenticatedInitiativesRouteImport.update({
    id: '/initiatives',
    path: '/initiatives',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedHypothesesRoute =
  ServerRequiredAuthenticatedHypothesesRouteImport.update({
    id: '/hypotheses',
    path: '/hypotheses',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedDocumentsRoute =
  ServerRequiredAuthenticatedDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedCreatedTasksRoute =
  ServerRequiredAuthenticatedCreatedTasksRouteImport.update({
    id: '/created-tasks',
    path: '/created-tasks',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedProfileIndexRoute =
  ServerRequiredAuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServerRequiredAuthenticatedProfileRoute,
  } as any)
const ServerRequiredAuthenticatedTasksTaskIdRoute =
  ServerRequiredAuthenticatedTasksTaskIdRouteImport.update({
    id: '/tasks_/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedTagsTagIdRoute =
  ServerRequiredAuthenticatedTagsTagIdRouteImport.update({
    id: '/tags_/$tagId',
    path: '/tags/$tagId',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsGuildRoute =
  ServerRequiredAuthenticatedSettingsGuildRouteImport.update({
    id: '/guild',
    path: '/guild',
    getParentRoute: () => ServerRequiredAuthenticatedSettingsRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsAdminRoute =
  ServerRequiredAuthenticatedSettingsAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => ServerRequiredAuthenticatedSettingsRoute,
  } as any)
const ServerRequiredAuthenticatedProjectsProjectIdRoute =
  ServerRequiredAuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects_/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedProfileSecurityRoute =
  ServerRequiredAuthenticatedProfileSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => ServerRequiredAuthenticatedProfileRoute,
  } as any)
const ServerRequiredAuthenticatedProfileNotificationsRoute =
  ServerRequiredAuthenticatedProfileNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ServerRequiredAuthenticatedProfileRoute,
  } as any)
const ServerRequiredAuthenticatedProfileInterfaceRoute =
  ServerRequiredAuthenticatedProfileInterfaceRouteImport.update({
    id: '/interface',
    path: '/interface',
    getParentRoute: () => ServerRequiredAuthenticatedProfileRoute,
  } as any)
const ServerRequiredAuthenticatedProfileImportRoute =
  ServerRequiredAuthenticatedProfileImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => ServerRequiredAuthenticatedProfileRoute,
  } as any)
const ServerRequiredAuthenticatedProfileDangerRoute =
  ServerRequiredAuthenticatedProfileDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => ServerRequiredAuthenticatedProfileRoute,
  } as any)
const ServerRequiredAuthenticatedProfileAiRoute =
  ServerRequiredAuthenticatedProfileAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => ServerRequiredAuthenticatedProfileRoute,
  } as any)
const ServerRequiredAuthenticatedInitiativesInitiativeIdRoute =
  ServerRequiredAuthenticatedInitiativesInitiativeIdRouteImport.update({
    id: '/initiatives_/$initiativeId',
    path: '/initiatives/$initiativeId',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedHypothesesHypothesisIdRoute =
  ServerRequiredAuthenticatedHypothesesHypothesisIdRouteImport.update({
    id: '/hypotheses_/$hypothesisId',
    path: '/hypotheses/$hypothesisId',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdRoute =
  ServerRequiredAuthenticatedGGuildIdRouteImport.update({
    id: '/g/$guildId',
    path: '/g/$guildId',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedDocumentsDocumentIdRoute =
  ServerRequiredAuthenticatedDocumentsDocumentIdRouteImport.update({
    id: '/documents_/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsGuildIndexRoute =
  ServerRequiredAuthenticatedSettingsGuildIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServerRequiredAuthenticatedSettingsGuildRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsAdminIndexRoute =
  ServerRequiredAuthenticatedSettingsAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServerRequiredAuthenticatedSettingsAdminRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdIndexRoute =
  ServerRequiredAuthenticatedGGuildIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsGuildUsersRoute =
  ServerRequiredAuthenticatedSettingsGuildUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ServerRequiredAuthenticatedSettingsGuildRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsGuildAiRoute =
  ServerRequiredAuthenticatedSettingsGuildAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => ServerRequiredAuthenticatedSettingsGuildRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsAdminUsersRoute =
  ServerRequiredAuthenticatedSettingsAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ServerRequiredAuthenticatedSettingsAdminRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsAdminEmailRoute =
  ServerRequiredAuthenticatedSettingsAdminEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => ServerRequiredAuthenticatedSettingsAdminRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsAdminBrandingRoute =
  ServerRequiredAuthenticatedSettingsAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => ServerRequiredAuthenticatedSettingsAdminRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsAdminAuthRoute =
  ServerRequiredAuthenticatedSettingsAdminAuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => ServerRequiredAuthenticatedSettingsAdminRoute,
  } as any)
const ServerRequiredAuthenticatedSettingsAdminAiRoute =
  ServerRequiredAuthenticatedSettingsAdminAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => ServerRequiredAuthenticatedSettingsAdminRoute,
  } as any)
const ServerRequiredAuthenticatedProjectsProjectIdSettingsRoute =
  ServerRequiredAuthenticatedProjectsProjectIdSettingsRouteImport.update({
    id: '/projects_/$projectId_/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedInitiativesInitiativeIdSettingsRoute =
  ServerRequiredAuthenticatedInitiativesInitiativeIdSettingsRouteImport.update({
    id: '/initiatives_/$initiativeId_/settings',
    path: '/initiatives/$initiativeId/settings',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdSettingsRoute =
  ServerRequiredAuthenticatedGGuildIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdQueuesRoute =
  ServerRequiredAuthenticatedGGuildIdQueuesRouteImport.update({
    id: '/queues',
    path: '/queues',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdProjectsRoute =
  ServerRequiredAuthenticatedGGuildIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdInitiativesRoute =
  ServerRequiredAuthenticatedGGuildIdInitiativesRouteImport.update({
    id: '/initiatives',
    path: '/initiatives',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdHypothesesRoute =
  ServerRequiredAuthenticatedGGuildIdHypothesesRouteImport.update({
    id: '/hypotheses',
    path: '/hypotheses',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdDocumentsRoute =
  ServerRequiredAuthenticatedGGuildIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedDocumentsDocumentIdSettingsRoute =
  ServerRequiredAuthenticatedDocumentsDocumentIdSettingsRouteImport.update({
    id: '/documents_/$documentId_/settings',
    path: '/documents/$documentId/settings',
    getParentRoute: () => ServerRequiredAuthenticatedRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdSettingsIndexRoute =
  ServerRequiredAuthenticatedGGuildIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdSettingsRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdTasksTaskIdRoute =
  ServerRequiredAuthenticatedGGuildIdTasksTaskIdRouteImport.update({
    id: '/tasks_/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdTagsTagIdRoute =
  ServerRequiredAuthenticatedGGuildIdTagsTagIdRouteImport.update({
    id: '/tags_/$tagId',
    path: '/tags/$tagId',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdSettingsUsersRoute =
  ServerRequiredAuthenticatedGGuildIdSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdSettingsRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdSettingsAiRoute =
  ServerRequiredAuthenticatedGGuildIdSettingsAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdSettingsRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdQueuesQueueIdRoute =
  ServerRequiredAuthenticatedGGuildIdQueuesQueueIdRouteImport.update({
    id: '/queues_/$queueId',
    path: '/queues/$queueId',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdProjectsProjectIdRoute =
  ServerRequiredAuthenticatedGGuildIdProjectsProjectIdRouteImport.update({
    id: '/projects_/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdRoute =
  ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdRouteImport.update({
    id: '/initiatives_/$initiativeId',
    path: '/initiatives/$initiativeId',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdHypothesesHypothesisIdRoute =
  ServerRequiredAuthenticatedGGuildIdHypothesesHypothesisIdRouteImport.update({
    id: '/hypotheses_/$hypothesisId',
    path: '/hypotheses/$hypothesisId',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdRoute =
  ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdRouteImport.update({
    id: '/documents_/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdQueuesQueueIdSettingsRoute =
  ServerRequiredAuthenticatedGGuildIdQueuesQueueIdSettingsRouteImport.update({
    id: '/queues_/$queueId_/settings',
    path: '/queues/$queueId/settings',
    getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
  } as any)
const ServerRequiredAuthenticatedGGuildIdProjectsProjectIdSettingsRoute =
  ServerRequiredAuthenticatedGGuildIdProjectsProjectIdSettingsRouteImport.update(
    {
      id: '/projects_/$projectId_/settings',
      path: '/projects/$projectId/settings',
      getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
    } as any,
  )
const ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdSettingsRoute =
  ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdSettingsRouteImport.update(
    {
      id: '/initiatives_/$initiativeId_/settings',
      path: '/initiatives/$initiativeId/settings',
      getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
    } as any,
  )
const ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdSettingsRoute =
  ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdSettingsRouteImport.update(
    {
      id: '/documents_/$documentId_/settings',
      path: '/documents/$documentId/settings',
      getParentRoute: () => ServerRequiredAuthenticatedGGuildIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof ServerRequiredAuthenticatedIndexRoute
  '/connect': typeof ConnectRoute
  '/forgot-password': typeof ServerRequiredForgotPasswordRoute
  '/login': typeof ServerRequiredLoginRoute
  '/register': typeof ServerRequiredRegisterRoute
  '/reset-password': typeof ServerRequiredResetPasswordRoute
  '/verify-email': typeof ServerRequiredVerifyEmailRoute
  '/welcome': typeof ServerRequiredWelcomeRoute
  '/created-tasks': typeof ServerRequiredAuthenticatedCreatedTasksRoute
  '/documents': typeof ServerRequiredAuthenticatedDocumentsRoute
  '/hypotheses': typeof ServerRequiredAuthenticatedHypothesesRoute
  '/initiatives': typeof ServerRequiredAuthenticatedInitiativesRoute
  '/my-documents': typeof ServerRequiredAuthenticatedMyDocumentsRoute
  '/my-projects': typeof ServerRequiredAuthenticatedMyProjectsRoute
  '/navigate': typeof ServerRequiredAuthenticatedNavigateRoute
  '/profile': typeof ServerRequiredAuthenticatedProfileRouteWithChildren
  '/projects': typeof ServerRequiredAuthenticatedProjectsRoute
  '/settings': typeof ServerRequiredAuthenticatedSettingsRouteWithChildren
  '/tasks': typeof ServerRequiredAuthenticatedTasksRoute
  '/user-stats': typeof ServerRequiredAuthenticatedUserStatsRoute
  '/invite/$code': typeof ServerRequiredInviteCodeRoute
  '/oidc/callback': typeof ServerRequiredOidcCallbackRoute
  '/documents/$documentId': typeof ServerRequiredAuthenticatedDocumentsDocumentIdRoute
  '/g/$guildId': typeof ServerRequiredAuthenticatedGGuildIdRouteWithChildren
  '/hypotheses/$hypothesisId': typeof ServerRequiredAuthenticatedHypothesesHypothesisIdRoute
  '/initiatives/$initiativeId': typeof ServerRequiredAuthenticatedInitiativesInitiativeIdRoute
  '/profile/ai': typeof ServerRequiredAuthenticatedProfileAiRoute
  '/profile/danger': typeof ServerRequiredAuthenticatedProfileDangerRoute
  '/profile/import': typeof ServerRequiredAuthenticatedProfileImportRoute
  '/profile/interface': typeof ServerRequiredAuthenticatedProfileInterfaceRoute
  '/profile/notifications': typeof ServerRequiredAuthenticatedProfileNotificationsRoute
  '/profile/security': typeof ServerRequiredAuthenticatedProfileSecurityRoute
  '/projects/$projectId': typeof ServerRequiredAuthenticatedProjectsProjectIdRoute
  '/settings/admin': typeof ServerRequiredAuthenticatedSettingsAdminRouteWithChildren
  '/settings/guild': typeof ServerRequiredAuthenticatedSettingsGuildRouteWithChildren
  '/tags/$tagId': typeof ServerRequiredAuthenticatedTagsTagIdRoute
  '/tasks/$taskId': typeof ServerRequiredAuthenticatedTasksTaskIdRoute
  '/profile/': typeof ServerRequiredAuthenticatedProfileIndexRoute
  '/documents/$documentId/settings': typeof ServerRequiredAuthenticatedDocumentsDocumentIdSettingsRoute
  '/g/$guildId/documents': typeof ServerRequiredAuthenticatedGGuildIdDocumentsRoute
  '/g/$guildId/hypotheses': typeof ServerRequiredAuthenticatedGGuildIdHypothesesRoute
  '/g/$guildId/initiatives': typeof ServerRequiredAuthenticatedGGuildIdInitiativesRoute
  '/g/$guildId/projects': typeof ServerRequiredAuthenticatedGGuildIdProjectsRoute
  '/g/$guildId/queues': typeof ServerRequiredAuthenticatedGGuildIdQueuesRoute
  '/g/$guildId/settings': typeof ServerRequiredAuthenticatedGGuildIdSettingsRouteWithChildren
  '/initiatives/$initiativeId/settings': typeof ServerRequiredAuthenticatedInitiativesInitiativeIdSettingsRoute
  '/projects/$projectId/settings': typeof ServerRequiredAuthenticatedProjectsProjectIdSettingsRoute
  '/settings/admin/ai': typeof ServerRequiredAuthenticatedSettingsAdminAiRoute
  '/settings/admin/auth': typeof ServerRequiredAuthenticatedSettingsAdminAuthRoute
  '/settings/admin/branding': typeof ServerRequiredAuthenticatedSettingsAdminBrandingRoute
  '/settings/admin/email': typeof ServerRequiredAuthenticatedSettingsAdminEmailRoute
  '/settings/admin/users': typeof ServerRequiredAuthenticatedSettingsAdminUsersRoute
  '/settings/guild/ai': typeof ServerRequiredAuthenticatedSettingsGuildAiRoute
  '/settings/guild/users': typeof ServerRequiredAuthenticatedSettingsGuildUsersRoute
  '/g/$guildId/': typeof ServerRequiredAuthenticatedGGuildIdIndexRoute
  '/settings/admin/': typeof ServerRequiredAuthenticatedSettingsAdminIndexRoute
  '/settings/guild/': typeof ServerRequiredAuthenticatedSettingsGuildIndexRoute
  '/g/$guildId/documents/$documentId': typeof ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdRoute
  '/g/$guildId/hypotheses/$hypothesisId': typeof ServerRequiredAuthenticatedGGuildIdHypothesesHypothesisIdRoute
  '/g/$guildId/initiatives/$initiativeId': typeof ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdRoute
  '/g/$guildId/projects/$projectId': typeof ServerRequiredAuthenticatedGGuildIdProjectsProjectIdRoute
  '/g/$guildId/queues/$queueId': typeof ServerRequiredAuthenticatedGGuildIdQueuesQueueIdRoute
  '/g/$guildId/settings/ai': typeof ServerRequiredAuthenticatedGGuildIdSettingsAiRoute
  '/g/$guildId/settings/users': typeof ServerRequiredAuthenticatedGGuildIdSettingsUsersRoute
  '/g/$guildId/tags/$tagId': typeof ServerRequiredAuthenticatedGGuildIdTagsTagIdRoute
  '/g/$guildId/tasks/$taskId': typeof ServerRequiredAuthenticatedGGuildIdTasksTaskIdRoute
  '/g/$guildId/settings/': typeof ServerRequiredAuthenticatedGGuildIdSettingsIndexRoute
  '/g/$guildId/documents/$documentId/settings': typeof ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdSettingsRoute
  '/g/$guildId/initiatives/$initiativeId/settings': typeof ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdSettingsRoute
  '/g/$guildId/projects/$projectId/settings': typeof ServerRequiredAuthenticatedGGuildIdProjectsProjectIdSettingsRoute
  '/g/$guildId/queues/$queueId/settings': typeof ServerRequiredAuthenticatedGGuildIdQueuesQueueIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof ServerRequiredAuthenticatedIndexRoute
  '/connect': typeof ConnectRoute
  '/forgot-password': typeof ServerRequiredForgotPasswordRoute
  '/login': typeof ServerRequiredLoginRoute
  '/register': typeof ServerRequiredRegisterRoute
  '/reset-password': typeof ServerRequiredResetPasswordRoute
  '/verify-email': typeof ServerRequiredVerifyEmailRoute
  '/welcome': typeof ServerRequiredWelcomeRoute
  '/created-tasks': typeof ServerRequiredAuthenticatedCreatedTasksRoute
  '/documents': typeof ServerRequiredAuthenticatedDocumentsRoute
  '/hypotheses': typeof ServerRequiredAuthenticatedHypothesesRoute
  '/initiatives': typeof ServerRequiredAuthenticatedInitiativesRoute
  '/my-documents': typeof ServerRequiredAuthenticatedMyDocumentsRoute
  '/my-projects': typeof ServerRequiredAuthenticatedMyProjectsRoute
  '/navigate': typeof ServerRequiredAuthenticatedNavigateRoute
  '/projects': typeof ServerRequiredAuthenticatedProjectsRoute
  '/settings': typeof ServerRequiredAuthenticatedSettingsRouteWithChildren
  '/tasks': typeof ServerRequiredAuthenticatedTasksRoute
  '/user-stats': typeof ServerRequiredAuthenticatedUserStatsRoute
  '/invite/$code': typeof ServerRequiredInviteCodeRoute
  '/oidc/callback': typeof ServerRequiredOidcCallbackRoute
  '/documents/$documentId': typeof ServerRequiredAuthenticatedDocumentsDocumentIdRoute
  '/hypotheses/$hypothesisId': typeof ServerRequiredAuthenticatedHypothesesHypothesisIdRoute
  '/initiatives/$initiativeId': typeof ServerRequiredAuthenticatedInitiativesInitiativeIdRoute
  '/profile/ai': typeof ServerRequiredAuthenticatedProfileAiRoute
  '/profile/danger': typeof ServerRequiredAuthenticatedProfileDangerRoute
  '/profile/import': typeof ServerRequiredAuthenticatedProfileImportRoute
  '/profile/interface': typeof ServerRequiredAuthenticatedProfileInterfaceRoute
  '/profile/notifications': typeof ServerRequiredAuthenticatedProfileNotificationsRoute
  '/profile/security': typeof ServerRequiredAuthenticatedProfileSecurityRoute
  '/projects/$projectId': typeof ServerRequiredAuthenticatedProjectsProjectIdRoute
  '/tags/$tagId': typeof ServerRequiredAuthenticatedTagsTagIdRoute
  '/tasks/$taskId': typeof ServerRequiredAuthenticatedTasksTaskIdRoute
  '/profile': typeof ServerRequiredAuthenticatedProfileIndexRoute
  '/documents/$documentId/settings': typeof ServerRequiredAuthenticatedDocumentsDocumentIdSettingsRoute
  '/g/$guildId/documents': typeof ServerRequiredAuthenticatedGGuildIdDocumentsRoute
  '/g/$guildId/hypotheses': typeof ServerRequiredAuthenticatedGGuildIdHypothesesRoute
  '/g/$guildId/initiatives': typeof ServerRequiredAuthenticatedGGuildIdInitiativesRoute
  '/g/$guildId/projects': typeof ServerRequiredAuthenticatedGGuildIdProjectsRoute
  '/g/$guildId/queues': typeof ServerRequiredAuthenticatedGGuildIdQueuesRoute
  '/initiatives/$initiativeId/settings': typeof ServerRequiredAuthenticatedInitiativesInitiativeIdSettingsRoute
  '/projects/$projectId/settings': typeof ServerRequiredAuthenticatedProjectsProjectIdSettingsRoute
  '/settings/admin/ai': typeof ServerRequiredAuthenticatedSettingsAdminAiRoute
  '/settings/admin/auth': typeof ServerRequiredAuthenticatedSettingsAdminAuthRoute
  '/settings/admin/branding': typeof ServerRequiredAuthenticatedSettingsAdminBrandingRoute
  '/settings/admin/email': typeof ServerRequiredAuthenticatedSettingsAdminEmailRoute
  '/settings/admin/users': typeof ServerRequiredAuthenticatedSettingsAdminUsersRoute
  '/settings/guild/ai': typeof ServerRequiredAuthenticatedSettingsGuildAiRoute
  '/settings/guild/users': typeof ServerRequiredAuthenticatedSettingsGuildUsersRoute
  '/g/$guildId': typeof ServerRequiredAuthenticatedGGuildIdIndexRoute
  '/settings/admin': typeof ServerRequiredAuthenticatedSettingsAdminIndexRoute
  '/settings/guild': typeof ServerRequiredAuthenticatedSettingsGuildIndexRoute
  '/g/$guildId/documents/$documentId': typeof ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdRoute
  '/g/$guildId/hypotheses/$hypothesisId': typeof ServerRequiredAuthenticatedGGuildIdHypothesesHypothesisIdRoute
  '/g/$guildId/initiatives/$initiativeId': typeof ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdRoute
  '/g/$guildId/projects/$projectId': typeof ServerRequiredAuthenticatedGGuildIdProjectsProjectIdRoute
  '/g/$guildId/queues/$queueId': typeof ServerRequiredAuthenticatedGGuildIdQueuesQueueIdRoute
  '/g/$guildId/settings/ai': typeof ServerRequiredAuthenticatedGGuildIdSettingsAiRoute
  '/g/$guildId/settings/users': typeof ServerRequiredAuthenticatedGGuildIdSettingsUsersRoute
  '/g/$guildId/tags/$tagId': typeof ServerRequiredAuthenticatedGGuildIdTagsTagIdRoute
  '/g/$guildId/tasks/$taskId': typeof ServerRequiredAuthenticatedGGuildIdTasksTaskIdRoute
  '/g/$guildId/settings': typeof ServerRequiredAuthenticatedGGuildIdSettingsIndexRoute
  '/g/$guildId/documents/$documentId/settings': typeof ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdSettingsRoute
  '/g/$guildId/initiatives/$initiativeId/settings': typeof ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdSettingsRoute
  '/g/$guildId/projects/$projectId/settings': typeof ServerRequiredAuthenticatedGGuildIdProjectsProjectIdSettingsRoute
  '/g/$guildId/queues/$queueId/settings': typeof ServerRequiredAuthenticatedGGuildIdQueuesQueueIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_serverRequired': typeof ServerRequiredRouteWithChildren
  '/connect': typeof ConnectRoute
  '/_serverRequired/_authenticated': typeof ServerRequiredAuthenticatedRouteWithChildren
  '/_serverRequired/forgot-password': typeof ServerRequiredForgotPasswordRoute
  '/_serverRequired/login': typeof ServerRequiredLoginRoute
  '/_serverRequired/register': typeof ServerRequiredRegisterRoute
  '/_serverRequired/reset-password': typeof ServerRequiredResetPasswordRoute
  '/_serverRequired/verify-email': typeof ServerRequiredVerifyEmailRoute
  '/_serverRequired/welcome': typeof ServerRequiredWelcomeRoute
  '/_serverRequired/_authenticated/created-tasks': typeof ServerRequiredAuthenticatedCreatedTasksRoute
  '/_serverRequired/_authenticated/documents': typeof ServerRequiredAuthenticatedDocumentsRoute
  '/_serverRequired/_authenticated/hypotheses': typeof ServerRequiredAuthenticatedHypothesesRoute
  '/_serverRequired/_authenticated/initiatives': typeof ServerRequiredAuthenticatedInitiativesRoute
  '/_serverRequired/_authenticated/my-documents': typeof ServerRequiredAuthenticatedMyDocumentsRoute
  '/_serverRequired/_authenticated/my-projects': typeof ServerRequiredAuthenticatedMyProjectsRoute
  '/_serverRequired/_authenticated/navigate': typeof ServerRequiredAuthenticatedNavigateRoute
  '/_serverRequired/_authenticated/profile': typeof ServerRequiredAuthenticatedProfileRouteWithChildren
  '/_serverRequired/_authenticated/projects': typeof ServerRequiredAuthenticatedProjectsRoute
  '/_serverRequired/_authenticated/settings': typeof ServerRequiredAuthenticatedSettingsRouteWithChildren
  '/_serverRequired/_authenticated/tasks': typeof ServerRequiredAuthenticatedTasksRoute
  '/_serverRequired/_authenticated/user-stats': typeof ServerRequiredAuthenticatedUserStatsRoute
  '/_serverRequired/invite/$code': typeof ServerRequiredInviteCodeRoute
  '/_serverRequired/oidc/callback': typeof ServerRequiredOidcCallbackRoute
  '/_serverRequired/_authenticated/': typeof ServerRequiredAuthenticatedIndexRoute
  '/_serverRequired/_authenticated/documents_/$documentId': typeof ServerRequiredAuthenticatedDocumentsDocumentIdRoute
  '/_serverRequired/_authenticated/g/$guildId': typeof ServerRequiredAuthenticatedGGuildIdRouteWithChildren
  '/_serverRequired/_authenticated/hypotheses_/$hypothesisId': typeof ServerRequiredAuthenticatedHypothesesHypothesisIdRoute
  '/_serverRequired/_authenticated/initiatives_/$initiativeId': typeof ServerRequiredAuthenticatedInitiativesInitiativeIdRoute
  '/_serverRequired/_authenticated/profile/ai': typeof ServerRequiredAuthenticatedProfileAiRoute
  '/_serverRequired/_authenticated/profile/danger': typeof ServerRequiredAuthenticatedProfileDangerRoute
  '/_serverRequired/_authenticated/profile/import': typeof ServerRequiredAuthenticatedProfileImportRoute
  '/_serverRequired/_authenticated/profile/interface': typeof ServerRequiredAuthenticatedProfileInterfaceRoute
  '/_serverRequired/_authenticated/profile/notifications': typeof ServerRequiredAuthenticatedProfileNotificationsRoute
  '/_serverRequired/_authenticated/profile/security': typeof ServerRequiredAuthenticatedProfileSecurityRoute
  '/_serverRequired/_authenticated/projects_/$projectId': typeof ServerRequiredAuthenticatedProjectsProjectIdRoute
  '/_serverRequired/_authenticated/settings/admin': typeof ServerRequiredAuthenticatedSettingsAdminRouteWithChildren
  '/_serverRequired/_authenticated/settings/guild': typeof ServerRequiredAuthenticatedSettingsGuildRouteWithChildren
  '/_serverRequired/_authenticated/tags_/$tagId': typeof ServerRequiredAuthenticatedTagsTagIdRoute
  '/_serverRequired/_authenticated/tasks_/$taskId': typeof ServerRequiredAuthenticatedTasksTaskIdRoute
  '/_serverRequired/_authenticated/profile/': typeof ServerRequiredAuthenticatedProfileIndexRoute
  '/_serverRequired/_authenticated/documents_/$documentId_/settings': typeof ServerRequiredAuthenticatedDocumentsDocumentIdSettingsRoute
  '/_serverRequired/_authenticated/g/$guildId/documents': typeof ServerRequiredAuthenticatedGGuildIdDocumentsRoute
  '/_serverRequired/_authenticated/g/$guildId/hypotheses': typeof ServerRequiredAuthenticatedGGuildIdHypothesesRoute
  '/_serverRequired/_authenticated/g/$guildId/initiatives': typeof ServerRequiredAuthenticatedGGuildIdInitiativesRoute
  '/_serverRequired/_authenticated/g/$guildId/projects': typeof ServerRequiredAuthenticatedGGuildIdProjectsRoute
  '/_serverRequired/_authenticated/g/$guildId/queues': typeof ServerRequiredAuthenticatedGGuildIdQueuesRoute
  '/_serverRequired/_authenticated/g/$guildId/settings': typeof ServerRequiredAuthenticatedGGuildIdSettingsRouteWithChildren
  '/_serverRequired/_authenticated/initiatives_/$initiativeId_/settings': typeof ServerRequiredAuthenticatedInitiativesInitiativeIdSettingsRoute
  '/_serverRequired/_authenticated/projects_/$projectId_/settings': typeof ServerRequiredAuthenticatedProjectsProjectIdSettingsRoute
  '/_serverRequired/_authenticated/settings/admin/ai': typeof ServerRequiredAuthenticatedSettingsAdminAiRoute
  '/_serverRequired/_authenticated/settings/admin/auth': typeof ServerRequiredAuthenticatedSettingsAdminAuthRoute
  '/_serverRequired/_authenticated/settings/admin/branding': typeof ServerRequiredAuthenticatedSettingsAdminBrandingRoute
  '/_serverRequired/_authenticated/settings/admin/email': typeof ServerRequiredAuthenticatedSettingsAdminEmailRoute
  '/_serverRequired/_authenticated/settings/admin/users': typeof ServerRequiredAuthenticatedSettingsAdminUsersRoute
  '/_serverRequired/_authenticated/settings/guild/ai': typeof ServerRequiredAuthenticatedSettingsGuildAiRoute
  '/_serverRequired/_authenticated/settings/guild/users': typeof ServerRequiredAuthenticatedSettingsGuildUsersRoute
  '/_serverRequired/_authenticated/g/$guildId/': typeof ServerRequiredAuthenticatedGGuildIdIndexRoute
  '/_serverRequired/_authenticated/settings/admin/': typeof ServerRequiredAuthenticatedSettingsAdminIndexRoute
  '/_serverRequired/_authenticated/settings/guild/': typeof ServerRequiredAuthenticatedSettingsGuildIndexRoute
  '/_serverRequired/_authenticated/g/$guildId/documents_/$documentId': typeof ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdRoute
  '/_serverRequired/_authenticated/g/$guildId/hypotheses_/$hypothesisId': typeof ServerRequiredAuthenticatedGGuildIdHypothesesHypothesisIdRoute
  '/_serverRequired/_authenticated/g/$guildId/initiatives_/$initiativeId': typeof ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdRoute
  '/_serverRequired/_authenticated/g/$guildId/projects_/$projectId': typeof ServerRequiredAuthenticatedGGuildIdProjectsProjectIdRoute
  '/_serverRequired/_authenticated/g/$guildId/queues_/$queueId': typeof ServerRequiredAuthenticatedGGuildIdQueuesQueueIdRoute
  '/_serverRequired/_authenticated/g/$guildId/settings/ai': typeof ServerRequiredAuthenticatedGGuildIdSettingsAiRoute
  '/_serverRequired/_authenticated/g/$guildId/settings/users': typeof ServerRequiredAuthenticatedGGuildIdSettingsUsersRoute
  '/_serverRequired/_authenticated/g/$guildId/tags_/$tagId': typeof ServerRequiredAuthenticatedGGuildIdTagsTagIdRoute
  '/_serverRequired/_authenticated/g/$guildId/tasks_/$taskId': typeof ServerRequiredAuthenticatedGGuildIdTasksTaskIdRoute
  '/_serverRequired/_authenticated/g/$guildId/settings/': typeof ServerRequiredAuthenticatedGGuildIdSettingsIndexRoute
  '/_serverRequired/_authenticated/g/$guildId/documents_/$documentId_/settings': typeof ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdSettingsRoute
  '/_serverRequired/_authenticated/g/$guildId/initiatives_/$initiativeId_/settings': typeof ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdSettingsRoute
  '/_serverRequired/_authenticated/g/$guildId/projects_/$projectId_/settings': typeof ServerRequiredAuthenticatedGGuildIdProjectsProjectIdSettingsRoute
  '/_serverRequired/_authenticated/g/$guildId/queues_/$queueId_/settings': typeof ServerRequiredAuthenticatedGGuildIdQueuesQueueIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/welcome'
    | '/created-tasks'
    | '/documents'
    | '/hypotheses'
    | '/initiatives'
    | '/my-documents'
    | '/my-projects'
    | '/navigate'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/user-stats'
    | '/invite/$code'
    | '/oidc/callback'
    | '/documents/$documentId'
    | '/g/$guildId'
    | '/hypotheses/$hypothesisId'
    | '/initiatives/$initiativeId'
    | '/profile/ai'
    | '/profile/danger'
    | '/profile/import'
    | '/profile/interface'
    | '/profile/notifications'
    | '/profile/security'
    | '/projects/$projectId'
    | '/settings/admin'
    | '/settings/guild'
    | '/tags/$tagId'
    | '/tasks/$taskId'
    | '/profile/'
    | '/documents/$documentId/settings'
    | '/g/$guildId/documents'
    | '/g/$guildId/hypotheses'
    | '/g/$guildId/initiatives'
    | '/g/$guildId/projects'
    | '/g/$guildId/queues'
    | '/g/$guildId/settings'
    | '/initiatives/$initiativeId/settings'
    | '/projects/$projectId/settings'
    | '/settings/admin/ai'
    | '/settings/admin/auth'
    | '/settings/admin/branding'
    | '/settings/admin/email'
    | '/settings/admin/users'
    | '/settings/guild/ai'
    | '/settings/guild/users'
    | '/g/$guildId/'
    | '/settings/admin/'
    | '/settings/guild/'
    | '/g/$guildId/documents/$documentId'
    | '/g/$guildId/hypotheses/$hypothesisId'
    | '/g/$guildId/initiatives/$initiativeId'
    | '/g/$guildId/projects/$projectId'
    | '/g/$guildId/queues/$queueId'
    | '/g/$guildId/settings/ai'
    | '/g/$guildId/settings/users'
    | '/g/$guildId/tags/$tagId'
    | '/g/$guildId/tasks/$taskId'
    | '/g/$guildId/settings/'
    | '/g/$guildId/documents/$documentId/settings'
    | '/g/$guildId/initiatives/$initiativeId/settings'
    | '/g/$guildId/projects/$projectId/settings'
    | '/g/$guildId/queues/$queueId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/welcome'
    | '/created-tasks'
    | '/documents'
    | '/hypotheses'
    | '/initiatives'
    | '/my-documents'
    | '/my-projects'
    | '/navigate'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/user-stats'
    | '/invite/$code'
    | '/oidc/callback'
    | '/documents/$documentId'
    | '/hypotheses/$hypothesisId'
    | '/initiatives/$initiativeId'
    | '/profile/ai'
    | '/profile/danger'
    | '/profile/import'
    | '/profile/interface'
    | '/profile/notifications'
    | '/profile/security'
    | '/projects/$projectId'
    | '/tags/$tagId'
    | '/tasks/$taskId'
    | '/profile'
    | '/documents/$documentId/settings'
    | '/g/$guildId/documents'
    | '/g/$guildId/hypotheses'
    | '/g/$guildId/initiatives'
    | '/g/$guildId/projects'
    | '/g/$guildId/queues'
    | '/initiatives/$initiativeId/settings'
    | '/projects/$projectId/settings'
    | '/settings/admin/ai'
    | '/settings/admin/auth'
    | '/settings/admin/branding'
    | '/settings/admin/email'
    | '/settings/admin/users'
    | '/settings/guild/ai'
    | '/settings/guild/users'
    | '/g/$guildId'
    | '/settings/admin'
    | '/settings/guild'
    | '/g/$guildId/documents/$documentId'
    | '/g/$guildId/hypotheses/$hypothesisId'
    | '/g/$guildId/initiatives/$initiativeId'
    | '/g/$guildId/projects/$projectId'
    | '/g/$guildId/queues/$queueId'
    | '/g/$guildId/settings/ai'
    | '/g/$guildId/settings/users'
    | '/g/$guildId/tags/$tagId'
    | '/g/$guildId/tasks/$taskId'
    | '/g/$guildId/settings'
    | '/g/$guildId/documents/$documentId/settings'
    | '/g/$guildId/initiatives/$initiativeId/settings'
    | '/g/$guildId/projects/$projectId/settings'
    | '/g/$guildId/queues/$queueId/settings'
  id:
    | '__root__'
    | '/_serverRequired'
    | '/connect'
    | '/_serverRequired/_authenticated'
    | '/_serverRequired/forgot-password'
    | '/_serverRequired/login'
    | '/_serverRequired/register'
    | '/_serverRequired/reset-password'
    | '/_serverRequired/verify-email'
    | '/_serverRequired/welcome'
    | '/_serverRequired/_authenticated/created-tasks'
    | '/_serverRequired/_authenticated/documents'
    | '/_serverRequired/_authenticated/hypotheses'
    | '/_serverRequired/_authenticated/initiatives'
    | '/_serverRequired/_authenticated/my-documents'
    | '/_serverRequired/_authenticated/my-projects'
    | '/_serverRequired/_authenticated/navigate'
    | '/_serverRequired/_authenticated/profile'
    | '/_serverRequired/_authenticated/projects'
    | '/_serverRequired/_authenticated/settings'
    | '/_serverRequired/_authenticated/tasks'
    | '/_serverRequired/_authenticated/user-stats'
    | '/_serverRequired/invite/$code'
    | '/_serverRequired/oidc/callback'
    | '/_serverRequired/_authenticated/'
    | '/_serverRequired/_authenticated/documents_/$documentId'
    | '/_serverRequired/_authenticated/g/$guildId'
    | '/_serverRequired/_authenticated/hypotheses_/$hypothesisId'
    | '/_serverRequired/_authenticated/initiatives_/$initiativeId'
    | '/_serverRequired/_authenticated/profile/ai'
    | '/_serverRequired/_authenticated/profile/danger'
    | '/_serverRequired/_authenticated/profile/import'
    | '/_serverRequired/_authenticated/profile/interface'
    | '/_serverRequired/_authenticated/profile/notifications'
    | '/_serverRequired/_authenticated/profile/security'
    | '/_serverRequired/_authenticated/projects_/$projectId'
    | '/_serverRequired/_authenticated/settings/admin'
    | '/_serverRequired/_authenticated/settings/guild'
    | '/_serverRequired/_authenticated/tags_/$tagId'
    | '/_serverRequired/_authenticated/tasks_/$taskId'
    | '/_serverRequired/_authenticated/profile/'
    | '/_serverRequired/_authenticated/documents_/$documentId_/settings'
    | '/_serverRequired/_authenticated/g/$guildId/documents'
    | '/_serverRequired/_authenticated/g/$guildId/hypotheses'
    | '/_serverRequired/_authenticated/g/$guildId/initiatives'
    | '/_serverRequired/_authenticated/g/$guildId/projects'
    | '/_serverRequired/_authenticated/g/$guildId/queues'
    | '/_serverRequired/_authenticated/g/$guildId/settings'
    | '/_serverRequired/_authenticated/initiatives_/$initiativeId_/settings'
    | '/_serverRequired/_authenticated/projects_/$projectId_/settings'
    | '/_serverRequired/_authenticated/settings/admin/ai'
    | '/_serverRequired/_authenticated/settings/admin/auth'
    | '/_serverRequired/_authenticated/settings/admin/branding'
    | '/_serverRequired/_authenticated/settings/admin/email'
    | '/_serverRequired/_authenticated/settings/admin/users'
    | '/_serverRequired/_authenticated/settings/guild/ai'
    | '/_serverRequired/_authenticated/settings/guild/users'
    | '/_serverRequired/_authenticated/g/$guildId/'
    | '/_serverRequired/_authenticated/settings/admin/'
    | '/_serverRequired/_authenticated/settings/guild/'
    | '/_serverRequired/_authenticated/g/$guildId/documents_/$documentId'
    | '/_serverRequired/_authenticated/g/$guildId/hypotheses_/$hypothesisId'
    | '/_serverRequired/_authenticated/g/$guildId/initiatives_/$initiativeId'
    | '/_serverRequired/_authenticated/g/$guildId/projects_/$projectId'
    | '/_serverRequired/_authenticated/g/$guildId/queues_/$queueId'
    | '/_serverRequired/_authenticated/g/$guildId/settings/ai'
    | '/_serverRequired/_authenticated/g/$guildId/settings/users'
    | '/_serverRequired/_authenticated/g/$guildId/tags_/$tagId'
    | '/_serverRequired/_authenticated/g/$guildId/tasks_/$taskId'
    | '/_serverRequired/_authenticated/g/$guildId/settings/'
    | '/_serverRequired/_authenticated/g/$guildId/documents_/$documentId_/settings'
    | '/_serverRequired/_authenticated/g/$guildId/initiatives_/$initiativeId_/settings'
    | '/_serverRequired/_authenticated/g/$guildId/projects_/$projectId_/settings'
    | '/_serverRequired/_authenticated/g/$guildId/queues_/$queueId_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ServerRequiredRoute: typeof ServerRequiredRouteWithChildren
  ConnectRoute: typeof ConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_serverRequired': {
      id: '/_serverRequired'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ServerRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_serverRequired/welcome': {
      id: '/_serverRequired/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof ServerRequiredWelcomeRouteImport
      parentRoute: typeof ServerRequiredRoute
    }
    '/_serverRequired/verify-email': {
      id: '/_serverRequired/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof ServerRequiredVerifyEmailRouteImport
      parentRoute: typeof ServerRequiredRoute
    }
    '/_serverRequired/reset-password': {
      id: '/_serverRequired/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ServerRequiredResetPasswordRouteImport
      parentRoute: typeof ServerRequiredRoute
    }
    '/_serverRequired/register': {
      id: '/_serverRequired/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof ServerRequiredRegisterRouteImport
      parentRoute: typeof ServerRequiredRoute
    }
    '/_serverRequired/login': {
      id: '/_serverRequired/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ServerRequiredLoginRouteImport
      parentRoute: typeof ServerRequiredRoute
    }
    '/_serverRequired/forgot-password': {
      id: '/_serverRequired/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ServerRequiredForgotPasswordRouteImport
      parentRoute: typeof ServerRequiredRoute
    }
    '/_serverRequired/_authenticated': {
      id: '/_serverRequired/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ServerRequiredAuthenticatedRouteImport
      parentRoute: typeof ServerRequiredRoute
    }
    '/_serverRequired/_authenticated/': {
      id: '/_serverRequired/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ServerRequiredAuthenticatedIndexRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/oidc/callback': {
      id: '/_serverRequired/oidc/callback'
      path: '/oidc/callback'
      fullPath: '/oidc/callback'
      preLoaderRoute: typeof ServerRequiredOidcCallbackRouteImport
      parentRoute: typeof ServerRequiredRoute
    }
    '/_serverRequired/invite/$code': {
      id: '/_serverRequired/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof ServerRequiredInviteCodeRouteImport
      parentRoute: typeof ServerRequiredRoute
    }
    '/_serverRequired/_authenticated/user-stats': {
      id: '/_serverRequired/_authenticated/user-stats'
      path: '/user-stats'
      fullPath: '/user-stats'
      preLoaderRoute: typeof ServerRequiredAuthenticatedUserStatsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/tasks': {
      id: '/_serverRequired/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ServerRequiredAuthenticatedTasksRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/settings': {
      id: '/_serverRequired/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/projects': {
      id: '/_serverRequired/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ServerRequiredAuthenticatedProjectsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/profile': {
      id: '/_serverRequired/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ServerRequiredAuthenticatedProfileRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/navigate': {
      id: '/_serverRequired/_authenticated/navigate'
      path: '/navigate'
      fullPath: '/navigate'
      preLoaderRoute: typeof ServerRequiredAuthenticatedNavigateRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/my-projects': {
      id: '/_serverRequired/_authenticated/my-projects'
      path: '/my-projects'
      fullPath: '/my-projects'
      preLoaderRoute: typeof ServerRequiredAuthenticatedMyProjectsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/my-documents': {
      id: '/_serverRequired/_authenticated/my-documents'
      path: '/my-documents'
      fullPath: '/my-documents'
      preLoaderRoute: typeof ServerRequiredAuthenticatedMyDocumentsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/initiatives': {
      id: '/_serverRequired/_authenticated/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof ServerRequiredAuthenticatedInitiativesRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/hypotheses': {
      id: '/_serverRequired/_authenticated/hypotheses'
      path: '/hypotheses'
      fullPath: '/hypotheses'
      preLoaderRoute: typeof ServerRequiredAuthenticatedHypothesesRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/documents': {
      id: '/_serverRequired/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ServerRequiredAuthenticatedDocumentsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/created-tasks': {
      id: '/_serverRequired/_authenticated/created-tasks'
      path: '/created-tasks'
      fullPath: '/created-tasks'
      preLoaderRoute: typeof ServerRequiredAuthenticatedCreatedTasksRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/profile/': {
      id: '/_serverRequired/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ServerRequiredAuthenticatedProfileIndexRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedProfileRoute
    }
    '/_serverRequired/_authenticated/tasks_/$taskId': {
      id: '/_serverRequired/_authenticated/tasks_/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/tags_/$tagId': {
      id: '/_serverRequired/_authenticated/tags_/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedTagsTagIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/settings/guild': {
      id: '/_serverRequired/_authenticated/settings/guild'
      path: '/guild'
      fullPath: '/settings/guild'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsGuildRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedSettingsRoute
    }
    '/_serverRequired/_authenticated/settings/admin': {
      id: '/_serverRequired/_authenticated/settings/admin'
      path: '/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsAdminRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedSettingsRoute
    }
    '/_serverRequired/_authenticated/projects_/$projectId': {
      id: '/_serverRequired/_authenticated/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/profile/security': {
      id: '/_serverRequired/_authenticated/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ServerRequiredAuthenticatedProfileSecurityRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedProfileRoute
    }
    '/_serverRequired/_authenticated/profile/notifications': {
      id: '/_serverRequired/_authenticated/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ServerRequiredAuthenticatedProfileNotificationsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedProfileRoute
    }
    '/_serverRequired/_authenticated/profile/interface': {
      id: '/_serverRequired/_authenticated/profile/interface'
      path: '/interface'
      fullPath: '/profile/interface'
      preLoaderRoute: typeof ServerRequiredAuthenticatedProfileInterfaceRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedProfileRoute
    }
    '/_serverRequired/_authenticated/profile/import': {
      id: '/_serverRequired/_authenticated/profile/import'
      path: '/import'
      fullPath: '/profile/import'
      preLoaderRoute: typeof ServerRequiredAuthenticatedProfileImportRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedProfileRoute
    }
    '/_serverRequired/_authenticated/profile/danger': {
      id: '/_serverRequired/_authenticated/profile/danger'
      path: '/danger'
      fullPath: '/profile/danger'
      preLoaderRoute: typeof ServerRequiredAuthenticatedProfileDangerRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedProfileRoute
    }
    '/_serverRequired/_authenticated/profile/ai': {
      id: '/_serverRequired/_authenticated/profile/ai'
      path: '/ai'
      fullPath: '/profile/ai'
      preLoaderRoute: typeof ServerRequiredAuthenticatedProfileAiRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedProfileRoute
    }
    '/_serverRequired/_authenticated/initiatives_/$initiativeId': {
      id: '/_serverRequired/_authenticated/initiatives_/$initiativeId'
      path: '/initiatives/$initiativeId'
      fullPath: '/initiatives/$initiativeId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedInitiativesInitiativeIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/hypotheses_/$hypothesisId': {
      id: '/_serverRequired/_authenticated/hypotheses_/$hypothesisId'
      path: '/hypotheses/$hypothesisId'
      fullPath: '/hypotheses/$hypothesisId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedHypothesesHypothesisIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/g/$guildId': {
      id: '/_serverRequired/_authenticated/g/$guildId'
      path: '/g/$guildId'
      fullPath: '/g/$guildId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/documents_/$documentId': {
      id: '/_serverRequired/_authenticated/documents_/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedDocumentsDocumentIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/settings/guild/': {
      id: '/_serverRequired/_authenticated/settings/guild/'
      path: '/'
      fullPath: '/settings/guild/'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsGuildIndexRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedSettingsGuildRoute
    }
    '/_serverRequired/_authenticated/settings/admin/': {
      id: '/_serverRequired/_authenticated/settings/admin/'
      path: '/'
      fullPath: '/settings/admin/'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsAdminIndexRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedSettingsAdminRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/': {
      id: '/_serverRequired/_authenticated/g/$guildId/'
      path: '/'
      fullPath: '/g/$guildId/'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdIndexRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/settings/guild/users': {
      id: '/_serverRequired/_authenticated/settings/guild/users'
      path: '/users'
      fullPath: '/settings/guild/users'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsGuildUsersRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedSettingsGuildRoute
    }
    '/_serverRequired/_authenticated/settings/guild/ai': {
      id: '/_serverRequired/_authenticated/settings/guild/ai'
      path: '/ai'
      fullPath: '/settings/guild/ai'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsGuildAiRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedSettingsGuildRoute
    }
    '/_serverRequired/_authenticated/settings/admin/users': {
      id: '/_serverRequired/_authenticated/settings/admin/users'
      path: '/users'
      fullPath: '/settings/admin/users'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsAdminUsersRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedSettingsAdminRoute
    }
    '/_serverRequired/_authenticated/settings/admin/email': {
      id: '/_serverRequired/_authenticated/settings/admin/email'
      path: '/email'
      fullPath: '/settings/admin/email'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsAdminEmailRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedSettingsAdminRoute
    }
    '/_serverRequired/_authenticated/settings/admin/branding': {
      id: '/_serverRequired/_authenticated/settings/admin/branding'
      path: '/branding'
      fullPath: '/settings/admin/branding'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsAdminBrandingRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedSettingsAdminRoute
    }
    '/_serverRequired/_authenticated/settings/admin/auth': {
      id: '/_serverRequired/_authenticated/settings/admin/auth'
      path: '/auth'
      fullPath: '/settings/admin/auth'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsAdminAuthRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedSettingsAdminRoute
    }
    '/_serverRequired/_authenticated/settings/admin/ai': {
      id: '/_serverRequired/_authenticated/settings/admin/ai'
      path: '/ai'
      fullPath: '/settings/admin/ai'
      preLoaderRoute: typeof ServerRequiredAuthenticatedSettingsAdminAiRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedSettingsAdminRoute
    }
    '/_serverRequired/_authenticated/projects_/$projectId_/settings': {
      id: '/_serverRequired/_authenticated/projects_/$projectId_/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ServerRequiredAuthenticatedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/initiatives_/$initiativeId_/settings': {
      id: '/_serverRequired/_authenticated/initiatives_/$initiativeId_/settings'
      path: '/initiatives/$initiativeId/settings'
      fullPath: '/initiatives/$initiativeId/settings'
      preLoaderRoute: typeof ServerRequiredAuthenticatedInitiativesInitiativeIdSettingsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/settings': {
      id: '/_serverRequired/_authenticated/g/$guildId/settings'
      path: '/settings'
      fullPath: '/g/$guildId/settings'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdSettingsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/queues': {
      id: '/_serverRequired/_authenticated/g/$guildId/queues'
      path: '/queues'
      fullPath: '/g/$guildId/queues'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdQueuesRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/projects': {
      id: '/_serverRequired/_authenticated/g/$guildId/projects'
      path: '/projects'
      fullPath: '/g/$guildId/projects'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdProjectsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/initiatives': {
      id: '/_serverRequired/_authenticated/g/$guildId/initiatives'
      path: '/initiatives'
      fullPath: '/g/$guildId/initiatives'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdInitiativesRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/hypotheses': {
      id: '/_serverRequired/_authenticated/g/$guildId/hypotheses'
      path: '/hypotheses'
      fullPath: '/g/$guildId/hypotheses'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdHypothesesRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/documents': {
      id: '/_serverRequired/_authenticated/g/$guildId/documents'
      path: '/documents'
      fullPath: '/g/$guildId/documents'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdDocumentsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/documents_/$documentId_/settings': {
      id: '/_serverRequired/_authenticated/documents_/$documentId_/settings'
      path: '/documents/$documentId/settings'
      fullPath: '/documents/$documentId/settings'
      preLoaderRoute: typeof ServerRequiredAuthenticatedDocumentsDocumentIdSettingsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/settings/': {
      id: '/_serverRequired/_authenticated/g/$guildId/settings/'
      path: '/'
      fullPath: '/g/$guildId/settings/'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdSettingsIndexRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdSettingsRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/tasks_/$taskId': {
      id: '/_serverRequired/_authenticated/g/$guildId/tasks_/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/g/$guildId/tasks/$taskId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdTasksTaskIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/tags_/$tagId': {
      id: '/_serverRequired/_authenticated/g/$guildId/tags_/$tagId'
      path: '/tags/$tagId'
      fullPath: '/g/$guildId/tags/$tagId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdTagsTagIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/settings/users': {
      id: '/_serverRequired/_authenticated/g/$guildId/settings/users'
      path: '/users'
      fullPath: '/g/$guildId/settings/users'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdSettingsUsersRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdSettingsRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/settings/ai': {
      id: '/_serverRequired/_authenticated/g/$guildId/settings/ai'
      path: '/ai'
      fullPath: '/g/$guildId/settings/ai'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdSettingsAiRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdSettingsRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/queues_/$queueId': {
      id: '/_serverRequired/_authenticated/g/$guildId/queues_/$queueId'
      path: '/queues/$queueId'
      fullPath: '/g/$guildId/queues/$queueId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdQueuesQueueIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/projects_/$projectId': {
      id: '/_serverRequired/_authenticated/g/$guildId/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/g/$guildId/projects/$projectId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdProjectsProjectIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/initiatives_/$initiativeId': {
      id: '/_serverRequired/_authenticated/g/$guildId/initiatives_/$initiativeId'
      path: '/initiatives/$initiativeId'
      fullPath: '/g/$guildId/initiatives/$initiativeId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/hypotheses_/$hypothesisId': {
      id: '/_serverRequired/_authenticated/g/$guildId/hypotheses_/$hypothesisId'
      path: '/hypotheses/$hypothesisId'
      fullPath: '/g/$guildId/hypotheses/$hypothesisId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdHypothesesHypothesisIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/documents_/$documentId': {
      id: '/_serverRequired/_authenticated/g/$guildId/documents_/$documentId'
      path: '/documents/$documentId'
      fullPath: '/g/$guildId/documents/$documentId'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/queues_/$queueId_/settings': {
      id: '/_serverRequired/_authenticated/g/$guildId/queues_/$queueId_/settings'
      path: '/queues/$queueId/settings'
      fullPath: '/g/$guildId/queues/$queueId/settings'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdQueuesQueueIdSettingsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/projects_/$projectId_/settings': {
      id: '/_serverRequired/_authenticated/g/$guildId/projects_/$projectId_/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/g/$guildId/projects/$projectId/settings'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/initiatives_/$initiativeId_/settings': {
      id: '/_serverRequired/_authenticated/g/$guildId/initiatives_/$initiativeId_/settings'
      path: '/initiatives/$initiativeId/settings'
      fullPath: '/g/$guildId/initiatives/$initiativeId/settings'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdSettingsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
    '/_serverRequired/_authenticated/g/$guildId/documents_/$documentId_/settings': {
      id: '/_serverRequired/_authenticated/g/$guildId/documents_/$documentId_/settings'
      path: '/documents/$documentId/settings'
      fullPath: '/g/$guildId/documents/$documentId/settings'
      preLoaderRoute: typeof ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdSettingsRouteImport
      parentRoute: typeof ServerRequiredAuthenticatedGGuildIdRoute
    }
  }
}

interface ServerRequiredAuthenticatedProfileRouteChildren {
  ServerRequiredAuthenticatedProfileAiRoute: typeof ServerRequiredAuthenticatedProfileAiRoute
  ServerRequiredAuthenticatedProfileDangerRoute: typeof ServerRequiredAuthenticatedProfileDangerRoute
  ServerRequiredAuthenticatedProfileImportRoute: typeof ServerRequiredAuthenticatedProfileImportRoute
  ServerRequiredAuthenticatedProfileInterfaceRoute: typeof ServerRequiredAuthenticatedProfileInterfaceRoute
  ServerRequiredAuthenticatedProfileNotificationsRoute: typeof ServerRequiredAuthenticatedProfileNotificationsRoute
  ServerRequiredAuthenticatedProfileSecurityRoute: typeof ServerRequiredAuthenticatedProfileSecurityRoute
  ServerRequiredAuthenticatedProfileIndexRoute: typeof ServerRequiredAuthenticatedProfileIndexRoute
}

const ServerRequiredAuthenticatedProfileRouteChildren: ServerRequiredAuthenticatedProfileRouteChildren =
  {
    ServerRequiredAuthenticatedProfileAiRoute:
      ServerRequiredAuthenticatedProfileAiRoute,
    ServerRequiredAuthenticatedProfileDangerRoute:
      ServerRequiredAuthenticatedProfileDangerRoute,
    ServerRequiredAuthenticatedProfileImportRoute:
      ServerRequiredAuthenticatedProfileImportRoute,
    ServerRequiredAuthenticatedProfileInterfaceRoute:
      ServerRequiredAuthenticatedProfileInterfaceRoute,
    ServerRequiredAuthenticatedProfileNotificationsRoute:
      ServerRequiredAuthenticatedProfileNotificationsRoute,
    ServerRequiredAuthenticatedProfileSecurityRoute:
      ServerRequiredAuthenticatedProfileSecurityRoute,
    ServerRequiredAuthenticatedProfileIndexRoute:
      ServerRequiredAuthenticatedProfileIndexRoute,
  }

const ServerRequiredAuthenticatedProfileRouteWithChildren =
  ServerRequiredAuthenticatedProfileRoute._addFileChildren(
    ServerRequiredAuthenticatedProfileRouteChildren,
  )

interface ServerRequiredAuthenticatedSettingsAdminRouteChildren {
  ServerRequiredAuthenticatedSettingsAdminAiRoute: typeof ServerRequiredAuthenticatedSettingsAdminAiRoute
  ServerRequiredAuthenticatedSettingsAdminAuthRoute: typeof ServerRequiredAuthenticatedSettingsAdminAuthRoute
  ServerRequiredAuthenticatedSettingsAdminBrandingRoute: typeof ServerRequiredAuthenticatedSettingsAdminBrandingRoute
  ServerRequiredAuthenticatedSettingsAdminEmailRoute: typeof ServerRequiredAuthenticatedSettingsAdminEmailRoute
  ServerRequiredAuthenticatedSettingsAdminUsersRoute: typeof ServerRequiredAuthenticatedSettingsAdminUsersRoute
  ServerRequiredAuthenticatedSettingsAdminIndexRoute: typeof ServerRequiredAuthenticatedSettingsAdminIndexRoute
}

const ServerRequiredAuthenticatedSettingsAdminRouteChildren: ServerRequiredAuthenticatedSettingsAdminRouteChildren =
  {
    ServerRequiredAuthenticatedSettingsAdminAiRoute:
      ServerRequiredAuthenticatedSettingsAdminAiRoute,
    ServerRequiredAuthenticatedSettingsAdminAuthRoute:
      ServerRequiredAuthenticatedSettingsAdminAuthRoute,
    ServerRequiredAuthenticatedSettingsAdminBrandingRoute:
      ServerRequiredAuthenticatedSettingsAdminBrandingRoute,
    ServerRequiredAuthenticatedSettingsAdminEmailRoute:
      ServerRequiredAuthenticatedSettingsAdminEmailRoute,
    ServerRequiredAuthenticatedSettingsAdminUsersRoute:
      ServerRequiredAuthenticatedSettingsAdminUsersRoute,
    ServerRequiredAuthenticatedSettingsAdminIndexRoute:
      ServerRequiredAuthenticatedSettingsAdminIndexRoute,
  }

const ServerRequiredAuthenticatedSettingsAdminRouteWithChildren =
  ServerRequiredAuthenticatedSettingsAdminRoute._addFileChildren(
    ServerRequiredAuthenticatedSettingsAdminRouteChildren,
  )

interface ServerRequiredAuthenticatedSettingsGuildRouteChildren {
  ServerRequiredAuthenticatedSettingsGuildAiRoute: typeof ServerRequiredAuthenticatedSettingsGuildAiRoute
  ServerRequiredAuthenticatedSettingsGuildUsersRoute: typeof ServerRequiredAuthenticatedSettingsGuildUsersRoute
  ServerRequiredAuthenticatedSettingsGuildIndexRoute: typeof ServerRequiredAuthenticatedSettingsGuildIndexRoute
}

const ServerRequiredAuthenticatedSettingsGuildRouteChildren: ServerRequiredAuthenticatedSettingsGuildRouteChildren =
  {
    ServerRequiredAuthenticatedSettingsGuildAiRoute:
      ServerRequiredAuthenticatedSettingsGuildAiRoute,
    ServerRequiredAuthenticatedSettingsGuildUsersRoute:
      ServerRequiredAuthenticatedSettingsGuildUsersRoute,
    ServerRequiredAuthenticatedSettingsGuildIndexRoute:
      ServerRequiredAuthenticatedSettingsGuildIndexRoute,
  }

const ServerRequiredAuthenticatedSettingsGuildRouteWithChildren =
  ServerRequiredAuthenticatedSettingsGuildRoute._addFileChildren(
    ServerRequiredAuthenticatedSettingsGuildRouteChildren,
  )

interface ServerRequiredAuthenticatedSettingsRouteChildren {
  ServerRequiredAuthenticatedSettingsAdminRoute: typeof ServerRequiredAuthenticatedSettingsAdminRouteWithChildren
  ServerRequiredAuthenticatedSettingsGuildRoute: typeof ServerRequiredAuthenticatedSettingsGuildRouteWithChildren
}

const ServerRequiredAuthenticatedSettingsRouteChildren: ServerRequiredAuthenticatedSettingsRouteChildren =
  {
    ServerRequiredAuthenticatedSettingsAdminRoute:
      ServerRequiredAuthenticatedSettingsAdminRouteWithChildren,
    ServerRequiredAuthenticatedSettingsGuildRoute:
      ServerRequiredAuthenticatedSettingsGuildRouteWithChildren,
  }

const ServerRequiredAuthenticatedSettingsRouteWithChildren =
  ServerRequiredAuthenticatedSettingsRoute._addFileChildren(
    ServerRequiredAuthenticatedSettingsRouteChildren,
  )

interface ServerRequiredAuthenticatedGGuildIdSettingsRouteChildren {
  ServerRequiredAuthenticatedGGuildIdSettingsAiRoute: typeof ServerRequiredAuthenticatedGGuildIdSettingsAiRoute
  ServerRequiredAuthenticatedGGuildIdSettingsUsersRoute: typeof ServerRequiredAuthenticatedGGuildIdSettingsUsersRoute
  ServerRequiredAuthenticatedGGuildIdSettingsIndexRoute: typeof ServerRequiredAuthenticatedGGuildIdSettingsIndexRoute
}

const ServerRequiredAuthenticatedGGuildIdSettingsRouteChildren: ServerRequiredAuthenticatedGGuildIdSettingsRouteChildren =
  {
    ServerRequiredAuthenticatedGGuildIdSettingsAiRoute:
      ServerRequiredAuthenticatedGGuildIdSettingsAiRoute,
    ServerRequiredAuthenticatedGGuildIdSettingsUsersRoute:
      ServerRequiredAuthenticatedGGuildIdSettingsUsersRoute,
    ServerRequiredAuthenticatedGGuildIdSettingsIndexRoute:
      ServerRequiredAuthenticatedGGuildIdSettingsIndexRoute,
  }

const ServerRequiredAuthenticatedGGuildIdSettingsRouteWithChildren =
  ServerRequiredAuthenticatedGGuildIdSettingsRoute._addFileChildren(
    ServerRequiredAuthenticatedGGuildIdSettingsRouteChildren,
  )

interface ServerRequiredAuthenticatedGGuildIdRouteChildren {
  ServerRequiredAuthenticatedGGuildIdDocumentsRoute: typeof ServerRequiredAuthenticatedGGuildIdDocumentsRoute
  ServerRequiredAuthenticatedGGuildIdHypothesesRoute: typeof ServerRequiredAuthenticatedGGuildIdHypothesesRoute
  ServerRequiredAuthenticatedGGuildIdInitiativesRoute: typeof ServerRequiredAuthenticatedGGuildIdInitiativesRoute
  ServerRequiredAuthenticatedGGuildIdProjectsRoute: typeof ServerRequiredAuthenticatedGGuildIdProjectsRoute
  ServerRequiredAuthenticatedGGuildIdQueuesRoute: typeof ServerRequiredAuthenticatedGGuildIdQueuesRoute
  ServerRequiredAuthenticatedGGuildIdSettingsRoute: typeof ServerRequiredAuthenticatedGGuildIdSettingsRouteWithChildren
  ServerRequiredAuthenticatedGGuildIdIndexRoute: typeof ServerRequiredAuthenticatedGGuildIdIndexRoute
  ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdRoute: typeof ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdRoute
  ServerRequiredAuthenticatedGGuildIdHypothesesHypothesisIdRoute: typeof ServerRequiredAuthenticatedGGuildIdHypothesesHypothesisIdRoute
  ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdRoute: typeof ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdRoute
  ServerRequiredAuthenticatedGGuildIdProjectsProjectIdRoute: typeof ServerRequiredAuthenticatedGGuildIdProjectsProjectIdRoute
  ServerRequiredAuthenticatedGGuildIdQueuesQueueIdRoute: typeof ServerRequiredAuthenticatedGGuildIdQueuesQueueIdRoute
  ServerRequiredAuthenticatedGGuildIdTagsTagIdRoute: typeof ServerRequiredAuthenticatedGGuildIdTagsTagIdRoute
  ServerRequiredAuthenticatedGGuildIdTasksTaskIdRoute: typeof ServerRequiredAuthenticatedGGuildIdTasksTaskIdRoute
  ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdSettingsRoute: typeof ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdSettingsRoute
  ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdSettingsRoute: typeof ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdSettingsRoute
  ServerRequiredAuthenticatedGGuildIdProjectsProjectIdSettingsRoute: typeof ServerRequiredAuthenticatedGGuildIdProjectsProjectIdSettingsRoute
  ServerRequiredAuthenticatedGGuildIdQueuesQueueIdSettingsRoute: typeof ServerRequiredAuthenticatedGGuildIdQueuesQueueIdSettingsRoute
}

const ServerRequiredAuthenticatedGGuildIdRouteChildren: ServerRequiredAuthenticatedGGuildIdRouteChildren =
  {
    ServerRequiredAuthenticatedGGuildIdDocumentsRoute:
      ServerRequiredAuthenticatedGGuildIdDocumentsRoute,
    ServerRequiredAuthenticatedGGuildIdHypothesesRoute:
      ServerRequiredAuthenticatedGGuildIdHypothesesRoute,
    ServerRequiredAuthenticatedGGuildIdInitiativesRoute:
      ServerRequiredAuthenticatedGGuildIdInitiativesRoute,
    ServerRequiredAuthenticatedGGuildIdProjectsRoute:
      ServerRequiredAuthenticatedGGuildIdProjectsRoute,
    ServerRequiredAuthenticatedGGuildIdQueuesRoute:
      ServerRequiredAuthenticatedGGuildIdQueuesRoute,
    ServerRequiredAuthenticatedGGuildIdSettingsRoute:
      ServerRequiredAuthenticatedGGuildIdSettingsRouteWithChildren,
    ServerRequiredAuthenticatedGGuildIdIndexRoute:
      ServerRequiredAuthenticatedGGuildIdIndexRoute,
    ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdRoute:
      ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdRoute,
    ServerRequiredAuthenticatedGGuildIdHypothesesHypothesisIdRoute:
      ServerRequiredAuthenticatedGGuildIdHypothesesHypothesisIdRoute,
    ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdRoute:
      ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdRoute,
    ServerRequiredAuthenticatedGGuildIdProjectsProjectIdRoute:
      ServerRequiredAuthenticatedGGuildIdProjectsProjectIdRoute,
    ServerRequiredAuthenticatedGGuildIdQueuesQueueIdRoute:
      ServerRequiredAuthenticatedGGuildIdQueuesQueueIdRoute,
    ServerRequiredAuthenticatedGGuildIdTagsTagIdRoute:
      ServerRequiredAuthenticatedGGuildIdTagsTagIdRoute,
    ServerRequiredAuthenticatedGGuildIdTasksTaskIdRoute:
      ServerRequiredAuthenticatedGGuildIdTasksTaskIdRoute,
    ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdSettingsRoute:
      ServerRequiredAuthenticatedGGuildIdDocumentsDocumentIdSettingsRoute,
    ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdSettingsRoute:
      ServerRequiredAuthenticatedGGuildIdInitiativesInitiativeIdSettingsRoute,
    ServerRequiredAuthenticatedGGuildIdProjectsProjectIdSettingsRoute:
      ServerRequiredAuthenticatedGGuildIdProjectsProjectIdSettingsRoute,
    ServerRequiredAuthenticatedGGuildIdQueuesQueueIdSettingsRoute:
      ServerRequiredAuthenticatedGGuildIdQueuesQueueIdSettingsRoute,
  }

const ServerRequiredAuthenticatedGGuildIdRouteWithChildren =
  ServerRequiredAuthenticatedGGuildIdRoute._addFileChildren(
    ServerRequiredAuthenticatedGGuildIdRouteChildren,
  )

interface ServerRequiredAuthenticatedRouteChildren {
  ServerRequiredAuthenticatedCreatedTasksRoute: typeof ServerRequiredAuthenticatedCreatedTasksRoute
  ServerRequiredAuthenticatedDocumentsRoute: typeof ServerRequiredAuthenticatedDocumentsRoute
  ServerRequiredAuthenticatedHypothesesRoute: typeof ServerRequiredAuthenticatedHypothesesRoute
  ServerRequiredAuthenticatedInitiativesRoute: typeof ServerRequiredAuthenticatedInitiativesRoute
  ServerRequiredAuthenticatedMyDocumentsRoute: typeof ServerRequiredAuthenticatedMyDocumentsRoute
  ServerRequiredAuthenticatedMyProjectsRoute: typeof ServerRequiredAuthenticatedMyProjectsRoute
  ServerRequiredAuthenticatedNavigateRoute: typeof ServerRequiredAuthenticatedNavigateRoute
  ServerRequiredAuthenticatedProfileRoute: typeof ServerRequiredAuthenticatedProfileRouteWithChildren
  ServerRequiredAuthenticatedProjectsRoute: typeof ServerRequiredAuthenticatedProjectsRoute
  ServerRequiredAuthenticatedSettingsRoute: typeof ServerRequiredAuthenticatedSettingsRouteWithChildren
  ServerRequiredAuthenticatedTasksRoute: typeof ServerRequiredAuthenticatedTasksRoute
  ServerRequiredAuthenticatedUserStatsRoute: typeof ServerRequiredAuthenticatedUserStatsRoute
  ServerRequiredAuthenticatedIndexRoute: typeof ServerRequiredAuthenticatedIndexRoute
  ServerRequiredAuthenticatedDocumentsDocumentIdRoute: typeof ServerRequiredAuthenticatedDocumentsDocumentIdRoute
  ServerRequiredAuthenticatedGGuildIdRoute: typeof ServerRequiredAuthenticatedGGuildIdRouteWithChildren
  ServerRequiredAuthenticatedHypothesesHypothesisIdRoute: typeof ServerRequiredAuthenticatedHypothesesHypothesisIdRoute
  ServerRequiredAuthenticatedInitiativesInitiativeIdRoute: typeof ServerRequiredAuthenticatedInitiativesInitiativeIdRoute
  ServerRequiredAuthenticatedProjectsProjectIdRoute: typeof ServerRequiredAuthenticatedProjectsProjectIdRoute
  ServerRequiredAuthenticatedTagsTagIdRoute: typeof ServerRequiredAuthenticatedTagsTagIdRoute
  ServerRequiredAuthenticatedTasksTaskIdRoute: typeof ServerRequiredAuthenticatedTasksTaskIdRoute
  ServerRequiredAuthenticatedDocumentsDocumentIdSettingsRoute: typeof ServerRequiredAuthenticatedDocumentsDocumentIdSettingsRoute
  ServerRequiredAuthenticatedInitiativesInitiativeIdSettingsRoute: typeof ServerRequiredAuthenticatedInitiativesInitiativeIdSettingsRoute
  ServerRequiredAuthenticatedProjectsProjectIdSettingsRoute: typeof ServerRequiredAuthenticatedProjectsProjectIdSettingsRoute
}

const ServerRequiredAuthenticatedRouteChildren: ServerRequiredAuthenticatedRouteChildren =
  {
    ServerRequiredAuthenticatedCreatedTasksRoute:
      ServerRequiredAuthenticatedCreatedTasksRoute,
    ServerRequiredAuthenticatedDocumentsRoute:
      ServerRequiredAuthenticatedDocumentsRoute,
    ServerRequiredAuthenticatedHypothesesRoute:
      ServerRequiredAuthenticatedHypothesesRoute,
    ServerRequiredAuthenticatedInitiativesRoute:
      ServerRequiredAuthenticatedInitiativesRoute,
    ServerRequiredAuthenticatedMyDocumentsRoute:
      ServerRequiredAuthenticatedMyDocumentsRoute,
    ServerRequiredAuthenticatedMyProjectsRoute:
      ServerRequiredAuthenticatedMyProjectsRoute,
    ServerRequiredAuthenticatedNavigateRoute:
      ServerRequiredAuthenticatedNavigateRoute,
    ServerRequiredAuthenticatedProfileRoute:
      ServerRequiredAuthenticatedProfileRouteWithChildren,
    ServerRequiredAuthenticatedProjectsRoute:
      ServerRequiredAuthenticatedProjectsRoute,
    ServerRequiredAuthenticatedSettingsRoute:
      ServerRequiredAuthenticatedSettingsRouteWithChildren,
    ServerRequiredAuthenticatedTasksRoute:
      ServerRequiredAuthenticatedTasksRoute,
    ServerRequiredAuthenticatedUserStatsRoute:
      ServerRequiredAuthenticatedUserStatsRoute,
    ServerRequiredAuthenticatedIndexRoute:
      ServerRequiredAuthenticatedIndexRoute,
    ServerRequiredAuthenticatedDocumentsDocumentIdRoute:
      ServerRequiredAuthenticatedDocumentsDocumentIdRoute,
    ServerRequiredAuthenticatedGGuildIdRoute:
      ServerRequiredAuthenticatedGGuildIdRouteWithChildren,
    ServerRequiredAuthenticatedHypothesesHypothesisIdRoute:
      ServerRequiredAuthenticatedHypothesesHypothesisIdRoute,
    ServerRequiredAuthenticatedInitiativesInitiativeIdRoute:
      ServerRequiredAuthenticatedInitiativesInitiativeIdRoute,
    ServerRequiredAuthenticatedProjectsProjectIdRoute:
      ServerRequiredAuthenticatedProjectsProjectIdRoute,
    ServerRequiredAuthenticatedTagsTagIdRoute:
      ServerRequiredAuthenticatedTagsTagIdRoute,
    ServerRequiredAuthenticatedTasksTaskIdRoute:
      ServerRequiredAuthenticatedTasksTaskIdRoute,
    ServerRequiredAuthenticatedDocumentsDocumentIdSettingsRoute:
      ServerRequiredAuthenticatedDocumentsDocumentIdSettingsRoute,
    ServerRequiredAuthenticatedInitiativesInitiativeIdSettingsRoute:
      ServerRequiredAuthenticatedInitiativesInitiativeIdSettingsRoute,
    ServerRequiredAuthenticatedProjectsProjectIdSettingsRoute:
      ServerRequiredAuthenticatedProjectsProjectIdSettingsRoute,
  }

const ServerRequiredAuthenticatedRouteWithChildren =
  ServerRequiredAuthenticatedRoute._addFileChildren(
    ServerRequiredAuthenticatedRouteChildren,
  )

interface ServerRequiredRouteChildren {
  ServerRequiredAuthenticatedRoute: typeof ServerRequiredAuthenticatedRouteWithChildren
  ServerRequiredForgotPasswordRoute: typeof ServerRequiredForgotPasswordRoute
  ServerRequiredLoginRoute: typeof ServerRequiredLoginRoute
  ServerRequiredRegisterRoute: typeof ServerRequiredRegisterRoute
  ServerRequiredResetPasswordRoute: typeof ServerRequiredResetPasswordRoute
  ServerRequiredVerifyEmailRoute: typeof ServerRequiredVerifyEmailRoute
  ServerRequiredWelcomeRoute: typeof ServerRequiredWelcomeRoute
  ServerRequiredInviteCodeRoute: typeof ServerRequiredInviteCodeRoute
  ServerRequiredOidcCallbackRoute: typeof ServerRequiredOidcCallbackRoute
}

const ServerRequiredRouteChildren: ServerRequiredRouteChildren = {
  ServerRequiredAuthenticatedRoute:
    ServerRequiredAuthenticatedRouteWithChildren,
  ServerRequiredForgotPasswordRoute: ServerRequiredForgotPasswordRoute,
  ServerRequiredLoginRoute: ServerRequiredLoginRoute,
  ServerRequiredRegisterRoute: ServerRequiredRegisterRoute,
  ServerRequiredResetPasswordRoute: ServerRequiredResetPasswordRoute,
  ServerRequiredVerifyEmailRoute: ServerRequiredVerifyEmailRoute,
  ServerRequiredWelcomeRoute: ServerRequiredWelcomeRoute,
  ServerRequiredInviteCodeRoute: ServerRequiredInviteCodeRoute,
  ServerRequiredOidcCallbackRoute: ServerRequiredOidcCallbackRoute,
}

const ServerRequiredRouteWithChildren = ServerRequiredRoute._addFileChildren(
  ServerRequiredRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ServerRequiredRoute: ServerRequiredRouteWithChildren,
  ConnectRoute: ConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
